// languages/typescript/svelte/src/App.svelte
<script lang="ts">
  import { appName } from "./config.js";
  import { exampleService } from "./services/exampleService.svelte.js";

  let items = $state(exampleService.list());

  function add(): void {
    const name = globalThis.prompt("Name?");
    if (name && name.trim()) {
      exampleService.create(name);
      items = exampleService.list();
    }
  }
</script>

<main>
  <h1>{appName}</h1>
  {#if error}
    <div role="alert">
      <h2>Something went wrong</h2>
      <pre>{error}</pre>
    </div>
  {:else}
    <section>
      <h2>Examples</h2>
      <button type="button" onclick={add}>Add</button>
      <ul>
        {#each items as item (item.id)}
          <li>{item.id}: {item.name}</li>
        {/each}
      </ul>
    </section>
  {/if}
</main>

// languages/typescript/react/src/App.tsx
import { useState } from "react";

import { exampleService, type ExampleItem } from "./services/exampleService.js";
import { ErrorBoundary } from "./ErrorBoundary.js";

function ExampleList(): React.JSX.Element {
  const [items, setItems] = useState<ExampleItem[]>(exampleService.list());

  function add(): void {
    const name = window.prompt("Name?");
    if (name && name.trim()) {
      exampleService.create(name);
      setItems(exampleService.list());
    }
  }

  return (
    <section>
      <h2>Examples</h2>
      <button type="button" onClick={add}>
        Add
      </button>
      <ul>
        {items.map((item) => (
          <li key={item.id}>
            {item.id}: {item.name}
          </li>
        ))}
      </ul>
    </section>
  );
}

export default function App(): React.JSX.Element {
  return (
    <ErrorBoundary>
      <main>
        <h1>ForgeBase React Starter</h1>
        <ExampleList />
      </main>
    </ErrorBoundary>
  );
}
